version: "3.6"

services:

  mysql_db:
    container_name: mysql-db
    image: mysql:8.0.15
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    entrypoint: sh -c "echo 'CREATE DATABASE IF NOT EXISTS automation;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db-init/scripts/:/docker-entrypoint-initdb.d/
    restart: always
    network_mode: bridge
   
  selenoid:
    image: "aerokube/selenoid"
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: bridge
    
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    network_mode: bridge

  selenoid-chrome:
    image: "selenoid/vnc:chrome_77.0"
    
volumes:
  mysql_data:

  